FROM golang:1.24.3 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Собираем шлюз
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/main ./gateway/main.go

# Шаг запуска
FROM alpine:latest

WORKDIR /app

# Копируем из /app builder в текущую (/app)
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]